language: node_js
node_js:
- stable
cache: npm
addons:
  apt: 
    packages:
      - awscli 
install:
- npm install
- npm run build
deploy: 
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master
