language: node_js
node_js:
- stable
cache: npm
matrix:
  allow_failures:
  - node_js: stable
addons:
  apt: 
    packages:
      - awscli 
install:
- npm install
- npm run build
before_install:
- openssl aes-256-cbc -K $encrypted_37e5a2a3979a_key -iv $encrypted_37e5a2a3979a_iv
  -in id_rsa.enc -out id_rsa -d
deploy: 
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master
