service: frontend

plugins:
  - serverless-finch

custom:
  client:
        distributionFolder: dist
        bucketName: frontend-dist
        indexDocument: index.html
        errorDocument: index.html 
provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: us-east-1
